# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'd:\PBL5\PBL5_app\PBL5-Car-Lisence-Plate-Recognition-Application-v2\My-App-PBL5\UI\main.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_CarLisence(object):
    def setupUi(self, CarLisence):
        CarLisence.setObjectName("CarLisence")
        CarLisence.resize(1417, 806)
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(9)
        CarLisence.setFont(font)
        CarLisence.setStyleSheet("QMainWindow{\n"
"    background-color: #f9f8fd;\n"
"}")
        self.centralwidget = QtWidgets.QWidget(CarLisence)
        self.centralwidget.setObjectName("centralwidget")
        self.user_2 = QtWidgets.QTabWidget(self.centralwidget)
        self.user_2.setGeometry(QtCore.QRect(0, -1, 1421, 801))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.user_2.setFont(font)
        self.user_2.setMouseTracking(True)
        self.user_2.setTabletTracking(True)
        self.user_2.setStyleSheet("QTabWidget {\n"
"    background-color: #fef2f2;\n"
"}")
        self.user_2.setObjectName("user_2")
        self.controlGate = QtWidgets.QWidget()
        self.controlGate.setObjectName("controlGate")
        self.frame = QtWidgets.QFrame(self.controlGate)
        self.frame.setGeometry(QtCore.QRect(-1, -31, 1291, 801))
        self.frame.setStyleSheet("QFrame {\n"
"    background-color: #fff;\n"
"}")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.groupBox_4 = QtWidgets.QGroupBox(self.frame)
        self.groupBox_4.setGeometry(QtCore.QRect(640, 40, 641, 721))
        self.groupBox_4.setMouseTracking(True)
        self.groupBox_4.setTabletTracking(False)
        self.groupBox_4.setStyleSheet("QGroupBox{\n"
"    background-color: #e7eaed;\n"
"    border: none;\n"
"    border-radius: 10px\n"
"}")
        self.groupBox_4.setTitle("")
        self.groupBox_4.setCheckable(False)
        self.groupBox_4.setObjectName("groupBox_4")
        self.txtUsername = QtWidgets.QLineEdit(self.groupBox_4)
        self.txtUsername.setGeometry(QtCore.QRect(180, 160, 401, 41))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.txtUsername.setFont(font)
        self.txtUsername.setStyleSheet("QLineEdit{\n"
"    border-radius: 20px;\n"
"    padding-left: 12px;\n"
"    color: #371881;\n"
"}")
        self.txtUsername.setText("")
        self.txtUsername.setObjectName("txtUsername")
        self.label_2 = QtWidgets.QLabel(self.groupBox_4)
        self.label_2.setGeometry(QtCore.QRect(30, 300, 540, 1))
        self.label_2.setStyleSheet("QLabel {\n"
"    background-color: #371881;\n"
"}")
        self.label_2.setText("")
        self.label_2.setObjectName("label_2")
        self.label_4 = QtWidgets.QLabel(self.groupBox_4)
        self.label_4.setGeometry(QtCore.QRect(30, 220, 540, 1))
        self.label_4.setStyleSheet("QLabel {\n"
"    background-color: #371881;\n"
"}")
        self.label_4.setText("")
        self.label_4.setObjectName("label_4")
        self.txtLicensePlate = QtWidgets.QLineEdit(self.groupBox_4)
        self.txtLicensePlate.setGeometry(QtCore.QRect(180, 240, 401, 41))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.txtLicensePlate.setFont(font)
        self.txtLicensePlate.setStyleSheet("QLineEdit{\n"
"    border-radius: 20px;\n"
"    padding-left: 12px;\n"
"    color: #371881;\n"
"}")
        self.txtLicensePlate.setText("")
        self.txtLicensePlate.setObjectName("txtLicensePlate")
        self.label_16 = QtWidgets.QLabel(self.groupBox_4)
        self.label_16.setGeometry(QtCore.QRect(30, 40, 671, 31))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_16.setFont(font)
        self.label_16.setStyleSheet("QLabel {\n"
"    color: qlineargradient(spread:pad, x1:1, y1:1, x2:0, y2:0, stop:0.306818 rgba(143, 0, 146, 255), stop:0.886364 rgba(0, 100, 245, 255));\n"
" background-color: #e7eaed;\n"
"}")
        self.label_16.setObjectName("label_16")
        self.label_14 = QtWidgets.QLabel(self.groupBox_4)
        self.label_14.setGeometry(QtCore.QRect(30, 170, 111, 31))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.label_14.setFont(font)
        self.label_14.setStyleSheet("QLabel {\n"
"    color: #371881;\n"
" background-color: #e7eaed;\n"
"}")
        self.label_14.setObjectName("label_14")
        self.label_15 = QtWidgets.QLabel(self.groupBox_4)
        self.label_15.setGeometry(QtCore.QRect(30, 250, 141, 31))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.label_15.setFont(font)
        self.label_15.setStyleSheet("QLabel {\n"
"    color: #371881;\n"
" background-color: #e7eaed;\n"
"}")
        self.label_15.setObjectName("label_15")
        self.label_lisence = QtWidgets.QLabel(self.groupBox_4)
        self.label_lisence.setGeometry(QtCore.QRect(20, 380, 591, 111))
        self.label_lisence.setStyleSheet("QLabel {\n"
"background-color: qlineargradient(spread:pad, x1:1, y1:1, x2:0, y2:0, stop:0.306818 rgba(143, 0, 146, 255), stop:0.886364 rgba(0, 100, 245, 255));\n"
"   border : none;\n"
"}")
        self.label_lisence.setText("")
        self.label_lisence.setObjectName("label_lisence")
        self.label_17 = QtWidgets.QLabel(self.groupBox_4)
        self.label_17.setGeometry(QtCore.QRect(30, 330, 221, 31))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.label_17.setFont(font)
        self.label_17.setStyleSheet("QLabel {\n"
"    color: #371881;\n"
" background-color: #e7eaed;\n"
"}")
        self.label_17.setObjectName("label_17")
        self.label_AddUserControl = QtWidgets.QLabel(self.groupBox_4)
        self.label_AddUserControl.setGeometry(QtCore.QRect(320, 560, 161, 31))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.label_AddUserControl.setFont(font)
        self.label_AddUserControl.setStyleSheet("QLabel {\n"
"    color: #371881;\n"
" background-color: #e7eaed;\n"
"}")
        self.label_AddUserControl.setObjectName("label_AddUserControl")
        self.btn_CreateNewUser = QtWidgets.QPushButton(self.groupBox_4)
        self.btn_CreateNewUser.setGeometry(QtCore.QRect(480, 560, 101, 31))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.btn_CreateNewUser.setFont(font)
        self.btn_CreateNewUser.setCursor(QtGui.QCursor(QtCore.Qt.OpenHandCursor))
        self.btn_CreateNewUser.setStyleSheet("\n"
"QPushButton#btnCancel {\n"
"   background-color:#f7085a;\n"
"   border : none;\n"
"   color: white;\n"
"   border-radius: 20px;\n"
"}")
        self.btn_CreateNewUser.setObjectName("btn_CreateNewUser")
        self.label_6 = QtWidgets.QLabel(self.frame)
        self.label_6.setGeometry(QtCore.QRect(630, 50, 1, 700))
        self.label_6.setStyleSheet("QLabel {\n"
"    background-color: #371881 !important;\n"
"}")
        self.label_6.setText("")
        self.label_6.setObjectName("label_6")
        self.groupBox = QtWidgets.QGroupBox(self.frame)
        self.groupBox.setGeometry(QtCore.QRect(10, 90, 611, 671))
        self.groupBox.setStyleSheet("QGroupBox{\n"
"    background-color: #e7eaed;\n"
"    border: none;\n"
"    border-radius: 10px\n"
"}")
        self.groupBox.setTitle("")
        self.groupBox.setObjectName("groupBox")
        self.btnOpen = QtWidgets.QPushButton(self.groupBox)
        self.btnOpen.setGeometry(QtCore.QRect(110, 600, 171, 41))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.btnOpen.setFont(font)
        self.btnOpen.setCursor(QtGui.QCursor(QtCore.Qt.OpenHandCursor))
        self.btnOpen.setStyleSheet("QPushButton#btnSave:hover:!pressed {\n"
"    opacity: 0.7;\n"
"    border-radius: 20px;\n"
"}\n"
"QPushButton#btnSave {\n"
"   background-color: #371881;\n"
"background-color: qlineargradient(spread:pad, x1:1, y1:1, x2:0, y2:0, stop:0.306818 rgba(143, 0, 146, 255), stop:0.886364 rgba(0, 100, 245, 255));\n"
"   border : none;\n"
"   color: white;\n"
"   border-radius: 20px;\n"
"}")
        self.btnOpen.setObjectName("btnOpen")
        self.lbCamera = QtWidgets.QLabel(self.groupBox)
        self.lbCamera.setGeometry(QtCore.QRect(10, 10, 591, 541))
        self.lbCamera.setStyleSheet("QLabel {\n"
"background-color: qlineargradient(spread:pad, x1:1, y1:1, x2:0, y2:0, stop:0.306818 rgba(143, 0, 146, 255), stop:0.886364 rgba(0, 100, 245, 255));\n"
"   border : none;\n"
"border-radius : 10px;\n"
"}")
        self.lbCamera.setText("")
        self.lbCamera.setObjectName("lbCamera")
        self.btnCancel = QtWidgets.QPushButton(self.groupBox)
        self.btnCancel.setGeometry(QtCore.QRect(320, 600, 171, 41))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.btnCancel.setFont(font)
        self.btnCancel.setCursor(QtGui.QCursor(QtCore.Qt.OpenHandCursor))
        self.btnCancel.setStyleSheet("\n"
"QPushButton#btnCancel {\n"
"   background-color:#f7085a;\n"
"   border : none;\n"
"   color: white;\n"
"   border-radius: 20px;\n"
"}")
        self.btnCancel.setObjectName("btnCancel")
        self.label_9 = QtWidgets.QLabel(self.frame)
        self.label_9.setEnabled(True)
        self.label_9.setGeometry(QtCore.QRect(80, 30, 81, 51))
        self.label_9.setTabletTracking(False)
        self.label_9.setStyleSheet("QLabel {\n"
"    backround-color: red;\n"
"}\n"
"")
        self.label_9.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.label_9.setFrameShadow(QtWidgets.QFrame.Plain)
        self.label_9.setText("")
        self.label_9.setPixmap(QtGui.QPixmap("C:/Users/DANALAP/.designer/imageUI/icons8-car.gif"))
        self.label_9.setScaledContents(True)
        self.label_9.setObjectName("label_9")
        self.label_19 = QtWidgets.QLabel(self.frame)
        self.label_19.setGeometry(QtCore.QRect(230, 40, 191, 31))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_19.setFont(font)
        self.label_19.setStyleSheet("QLabel {\n"
"    color: qlineargradient(spread:pad, x1:1, y1:1, x2:0, y2:0, stop:0.306818 rgba(143, 0, 146, 255), stop:0.886364 rgba(0, 100, 245, 255));\n"
" background-color: #e7eaed;\n"
" background-color: #fff;\n"
"}")
        self.label_19.setObjectName("label_19")
        self.user_2.addTab(self.controlGate, "")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.frame_2 = QtWidgets.QFrame(self.tab)
        self.frame_2.setGeometry(QtCore.QRect(0, -30, 1411, 811))
        self.frame_2.setStyleSheet("QFrame {\n"
"    background-color: #fff;\n"
"}")
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.groupBox_5 = QtWidgets.QGroupBox(self.frame_2)
        self.groupBox_5.setGeometry(QtCore.QRect(50, 160, 1321, 601))
        self.groupBox_5.setMouseTracking(True)
        self.groupBox_5.setTabletTracking(False)
        self.groupBox_5.setStyleSheet("QGroupBox{\n"
"    background-color: #e7eaed;\n"
"    border: none;\n"
"    border-radius: 10px\n"
"}")
        self.groupBox_5.setTitle("")
        self.groupBox_5.setCheckable(False)
        self.groupBox_5.setObjectName("groupBox_5")
        self.tableHistory = QtWidgets.QTableWidget(self.groupBox_5)
        self.tableHistory.setGeometry(QtCore.QRect(70, 120, 1181, 371))
        self.tableHistory.setMaximumSize(QtCore.QSize(16777215, 371))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.tableHistory.setFont(font)
        self.tableHistory.setStyleSheet("QTableWidget::item#tableHistory {\n"
"      text-align : center;\n"
"      vertical-align: middle;\n"
"    background-color: #fff;\n"
"    color: #371881;\n"
"}\n"
"\n"
"QHeaderView, QHeaderView::section {\n"
"    background-color: #6a4bff;\n"
"    color: #fff;\n"
"    font-style: bold;\n"
"    text-align : center;\n"
"    font-size : 18px;\n"
"}\n"
"QTableWidget::item:selected#tableHistory { \n"
"    background-color: #ffedca; \n"
"}")
        self.tableHistory.setHorizontalScrollMode(QtWidgets.QAbstractItemView.ScrollPerItem)
        self.tableHistory.setColumnCount(5)
        self.tableHistory.setObjectName("tableHistory")
        self.tableHistory.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tableHistory.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableHistory.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableHistory.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableHistory.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableHistory.setHorizontalHeaderItem(4, item)
        self.tableHistory.verticalHeader().setVisible(False)
        self.btnSearchHistory = QtWidgets.QPushButton(self.groupBox_5)
        self.btnSearchHistory.setGeometry(QtCore.QRect(390, 30, 141, 41))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.btnSearchHistory.setFont(font)
        self.btnSearchHistory.setCursor(QtGui.QCursor(QtCore.Qt.OpenHandCursor))
        self.btnSearchHistory.setStyleSheet("QPushButton#btnSearchHistory {\n"
"   background-color: #371881;\n"
"   border : none;\n"
"   color: white;\n"
"   border-radius: 20px;\n"
"}")
        self.btnSearchHistory.setObjectName("btnSearchHistory")
        self.btnSortHistoryIncrease = QtWidgets.QPushButton(self.groupBox_5)
        self.btnSortHistoryIncrease.setGeometry(QtCore.QRect(1000, 30, 141, 41))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.btnSortHistoryIncrease.setFont(font)
        self.btnSortHistoryIncrease.setCursor(QtGui.QCursor(QtCore.Qt.OpenHandCursor))
        self.btnSortHistoryIncrease.setStyleSheet("QPushButton#btnSortHistoryIncrease {\n"
"   background-color: #371881;\n"
"   border : none;\n"
"   color: white;\n"
"   border-radius: 20px;\n"
"}")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("d:\\PBL5\\PBL5_app\\PBL5-Car-Lisence-Plate-Recognition-Application-v2\\My-App-PBL5\\UI\\../imageUI/up-arrow.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btnSortHistoryIncrease.setIcon(icon)
        self.btnSortHistoryIncrease.setIconSize(QtCore.QSize(30, 30))
        self.btnSortHistoryIncrease.setObjectName("btnSortHistoryIncrease")
        self.txtSearchHistory = QtWidgets.QLineEdit(self.groupBox_5)
        self.txtSearchHistory.setGeometry(QtCore.QRect(100, 30, 271, 41))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.txtSearchHistory.setFont(font)
        self.txtSearchHistory.setStyleSheet("QLineEdit{\n"
"    border-radius: 20px;\n"
"    padding-left: 12px;\n"
"    color: #371881;\n"
"}")
        self.txtSearchHistory.setText("")
        self.txtSearchHistory.setObjectName("txtSearchHistory")
        self.label_11 = QtWidgets.QLabel(self.groupBox_5)
        self.label_11.setGeometry(QtCore.QRect(660, 20, 71, 61))
        self.label_11.setStyleSheet("    background-color: #e7eaed;")
        self.label_11.setText("")
        self.label_11.setPixmap(QtGui.QPixmap("d:\\PBL5\\PBL5_app\\PBL5-Car-Lisence-Plate-Recognition-Application-v2\\My-App-PBL5\\UI\\../imageUI/sort.png"))
        self.label_11.setScaledContents(True)
        self.label_11.setObjectName("label_11")
        self.label_13 = QtWidgets.QLabel(self.groupBox_5)
        self.label_13.setGeometry(QtCore.QRect(20, 20, 71, 61))
        self.label_13.setStyleSheet("    background-color: #e7eaed;")
        self.label_13.setText("")
        self.label_13.setPixmap(QtGui.QPixmap("d:\\PBL5\\PBL5_app\\PBL5-Car-Lisence-Plate-Recognition-Application-v2\\My-App-PBL5\\UI\\../imageUI/search_1.png"))
        self.label_13.setScaledContents(True)
        self.label_13.setObjectName("label_13")
        self.btnSortHistoryDecrease = QtWidgets.QPushButton(self.groupBox_5)
        self.btnSortHistoryDecrease.setGeometry(QtCore.QRect(1160, 30, 141, 41))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.btnSortHistoryDecrease.setFont(font)
        self.btnSortHistoryDecrease.setCursor(QtGui.QCursor(QtCore.Qt.OpenHandCursor))
        self.btnSortHistoryDecrease.setStyleSheet("QPushButton#btnSortHistoryDecrease {\n"
"   background-color: #371881;\n"
"   border : none;\n"
"   color: white;\n"
"   border-radius: 20px;\n"
"}")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("d:\\PBL5\\PBL5_app\\PBL5-Car-Lisence-Plate-Recognition-Application-v2\\My-App-PBL5\\UI\\../imageUI/decrease.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btnSortHistoryDecrease.setIcon(icon1)
        self.btnSortHistoryDecrease.setIconSize(QtCore.QSize(25, 25))
        self.btnSortHistoryDecrease.setObjectName("btnSortHistoryDecrease")
        self.cbbSortHistory = QtWidgets.QComboBox(self.groupBox_5)
        self.cbbSortHistory.setGeometry(QtCore.QRect(740, 30, 241, 41))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.cbbSortHistory.setFont(font)
        self.cbbSortHistory.setStyleSheet("border-radius: 20px;\n"
"    padding-left: 15px;\n"
"    color: #371881;")
        self.cbbSortHistory.setObjectName("cbbSortHistory")
        self.cbbSortHistory.addItem("")
        self.cbbSortHistory.addItem("")
        self.cbbSortHistory.addItem("")
        self.cbbSortHistory.addItem("")
        self.cbbSortHistory.addItem("")
        self.btnResetHistory = QtWidgets.QPushButton(self.groupBox_5)
        self.btnResetHistory.setGeometry(QtCore.QRect(420, 520, 171, 41))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.btnResetHistory.setFont(font)
        self.btnResetHistory.setCursor(QtGui.QCursor(QtCore.Qt.OpenHandCursor))
        self.btnResetHistory.setStyleSheet("QPushButton#btnResetHistory {\n"
"   background-color: #743de3;\n"
"   border : none;\n"
"   color: white;\n"
"   border-radius: 20px;\n"
"}")
        self.btnResetHistory.setObjectName("btnResetHistory")
        self.btnDetailsHistory = QtWidgets.QPushButton(self.groupBox_5)
        self.btnDetailsHistory.setGeometry(QtCore.QRect(760, 520, 201, 41))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.btnDetailsHistory.setFont(font)
        self.btnDetailsHistory.setCursor(QtGui.QCursor(QtCore.Qt.OpenHandCursor))
        self.btnDetailsHistory.setStyleSheet("QPushButton#btnDetailsHistory:hover:!pressed {\n"
"    opacity: 0.7;\n"
"    border-radius: 20px;\n"
"}\n"
"QPushButton#btnDetailsHistory {\n"
"   background-color: #371881;\n"
"background-color: qlineargradient(spread:pad, x1:1, y1:1, x2:0, y2:0, stop:0.306818 rgba(143, 0, 146, 255), stop:0.886364 rgba(0, 100, 245, 255));\n"
"   border : none;\n"
"   color: white;\n"
"   border-radius: 20px;\n"
"}")
        self.btnDetailsHistory.setObjectName("btnDetailsHistory")
        self.label_10 = QtWidgets.QLabel(self.frame_2)
        self.label_10.setEnabled(True)
        self.label_10.setGeometry(QtCore.QRect(30, 40, 131, 91))
        self.label_10.setTabletTracking(False)
        self.label_10.setStyleSheet("QLabel {\n"
"    backround-color: red;\n"
"}\n"
"")
        self.label_10.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.label_10.setFrameShadow(QtWidgets.QFrame.Plain)
        self.label_10.setText("")
        self.label_10.setPixmap(QtGui.QPixmap(":/icon/icons8-car-badge-96.png"))
        self.label_10.setScaledContents(True)
        self.label_10.setObjectName("label_10")
        self.label_18 = QtWidgets.QLabel(self.frame_2)
        self.label_18.setGeometry(QtCore.QRect(170, 70, 571, 41))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.label_18.setFont(font)
        self.label_18.setStyleSheet("QLabel {\n"
"    color: qlineargradient(spread:pad, x1:1, y1:1, x2:0, y2:0, stop:0.306818 rgba(143, 0, 146, 255), stop:0.886364 rgba(0, 100, 245, 255));\n"
" background-color: #e7eaed;\n"
"\n"
" background-color: #fff;\n"
"}")
        self.label_18.setObjectName("label_18")
        self.label_31 = QtWidgets.QLabel(self.frame_2)
        self.label_31.setEnabled(True)
        self.label_31.setGeometry(QtCore.QRect(730, 40, 161, 91))
        self.label_31.setTabletTracking(False)
        self.label_31.setStyleSheet("QLabel {\n"
"    backround-color: red;\n"
"}\n"
"")
        self.label_31.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.label_31.setFrameShadow(QtWidgets.QFrame.Plain)
        self.label_31.setText("")
        self.label_31.setPixmap(QtGui.QPixmap(":/icon/icon-deco.png"))
        self.label_31.setScaledContents(True)
        self.label_31.setObjectName("label_31")
        self.label_32 = QtWidgets.QLabel(self.frame_2)
        self.label_32.setEnabled(True)
        self.label_32.setGeometry(QtCore.QRect(1070, 40, 161, 91))
        self.label_32.setTabletTracking(False)
        self.label_32.setStyleSheet("QLabel {\n"
"    backround-color: red;\n"
"}\n"
"")
        self.label_32.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.label_32.setFrameShadow(QtWidgets.QFrame.Plain)
        self.label_32.setText("")
        self.label_32.setPixmap(QtGui.QPixmap(":/icon/icon-deco.png"))
        self.label_32.setScaledContents(True)
        self.label_32.setObjectName("label_32")
        self.user_2.addTab(self.tab, "")
        self.User = QtWidgets.QWidget()
        self.User.setObjectName("User")
        self.frame_3 = QtWidgets.QFrame(self.User)
        self.frame_3.setGeometry(QtCore.QRect(-30, 0, 1511, 771))
        self.frame_3.setStyleSheet("QFrame {\n"
"    background-color: #fff;\n"
"}")
        self.frame_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_3.setObjectName("frame_3")
        self.groupBox_3 = QtWidgets.QGroupBox(self.frame_3)
        self.groupBox_3.setGeometry(QtCore.QRect(50, 120, 1361, 641))
        self.groupBox_3.setStyleSheet("QGroupBox{\n"
"    background-color: #e7eaed;\n"
"    border: none;\n"
"    border-radius: 10px\n"
"}")
        self.groupBox_3.setTitle("")
        self.groupBox_3.setObjectName("groupBox_3")
        self.tableUser = QtWidgets.QTableWidget(self.groupBox_3)
        self.tableUser.setGeometry(QtCore.QRect(50, 140, 1271, 371))
        self.tableUser.setMaximumSize(QtCore.QSize(16777215, 371))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.tableUser.setFont(font)
        self.tableUser.setStyleSheet("QTableWidget::item#tableUser {\n"
"      text-align : center;\n"
"      vertical-align: middle;\n"
"    background-color: #fff;\n"
"    color: #371881;\n"
"}\n"
"\n"
"QHeaderView, QHeaderView::section {\n"
"    background-color: #6a4bff;\n"
"    color: #fff;\n"
"    font-style: bold;\n"
"    text-align : center;\n"
"    font-size : 18px;\n"
"}\n"
"QTableWidget::item:selected#tableUser { \n"
"    background-color: #ffedca; \n"
"}")
        self.tableUser.setIconSize(QtCore.QSize(20, 20))
        self.tableUser.setHorizontalScrollMode(QtWidgets.QAbstractItemView.ScrollPerItem)
        self.tableUser.setColumnCount(7)
        self.tableUser.setObjectName("tableUser")
        self.tableUser.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tableUser.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableUser.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableUser.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableUser.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableUser.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableUser.setHorizontalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableUser.setHorizontalHeaderItem(6, item)
        self.tableUser.verticalHeader().setVisible(False)
        self.btnAddUser = QtWidgets.QPushButton(self.groupBox_3)
        self.btnAddUser.setGeometry(QtCore.QRect(450, 550, 201, 41))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.btnAddUser.setFont(font)
        self.btnAddUser.setCursor(QtGui.QCursor(QtCore.Qt.OpenHandCursor))
        self.btnAddUser.setStyleSheet("QPushButton#btnAddUser:hover:!pressed {\n"
"    opacity: 0.7;\n"
"    border-radius: 20px;\n"
"}\n"
"QPushButton#btnAddUser {\n"
"   background-color: #371881;\n"
"background-color: qlineargradient(spread:pad, x1:1, y1:1, x2:0, y2:0, stop:0.306818 rgba(143, 0, 146, 255), stop:0.886364 rgba(0, 100, 245, 255));\n"
"   border : none;\n"
"   color: white;\n"
"   border-radius: 20px;\n"
"}")
        self.btnAddUser.setObjectName("btnAddUser")
        self.btnUpdateUser = QtWidgets.QPushButton(self.groupBox_3)
        self.btnUpdateUser.setGeometry(QtCore.QRect(760, 550, 211, 41))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.btnUpdateUser.setFont(font)
        self.btnUpdateUser.setCursor(QtGui.QCursor(QtCore.Qt.OpenHandCursor))
        self.btnUpdateUser.setStyleSheet("QPushButton#btnUpdateUser:hover:!pressed {\n"
"    opacity: 0.7;\n"
"    border-radius: 20px;\n"
"}\n"
"QPushButton#btnUpdateUser {\n"
"   background-color: #371881;\n"
"background-color: qlineargradient(spread:pad, x1:1, y1:1, x2:0, y2:0, stop:0.306818 rgba(0, 100, 245, 255), stop:0.886364 rgba(143, 0, 146, 255));\n"
"   border : none;\n"
"   color: white;\n"
"   border-radius: 20px;\n"
"}")
        self.btnUpdateUser.setObjectName("btnUpdateUser")
        self.btnDelUser = QtWidgets.QPushButton(self.groupBox_3)
        self.btnDelUser.setGeometry(QtCore.QRect(1080, 550, 191, 41))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.btnDelUser.setFont(font)
        self.btnDelUser.setCursor(QtGui.QCursor(QtCore.Qt.OpenHandCursor))
        self.btnDelUser.setStyleSheet("QPushButton#btnDelUser:hover:!pressed {\n"
"\n"
"    border-radius: 20px;\n"
"}\n"
"QPushButton#btnDelUser {\n"
"   background-color: #371881;\n"
"background-color:#f7085a;\n"
"   border : none;\n"
"   color: white;\n"
"   border-radius: 20px;\n"
"}")
        self.btnDelUser.setObjectName("btnDelUser")
        self.txtSearchUser = QtWidgets.QLineEdit(self.groupBox_3)
        self.txtSearchUser.setGeometry(QtCore.QRect(100, 40, 271, 41))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.txtSearchUser.setFont(font)
        self.txtSearchUser.setStyleSheet("QLineEdit{\n"
"    border-radius: 20px;\n"
"    padding-left: 12px;\n"
"    color: #371881;\n"
"}")
        self.txtSearchUser.setText("")
        self.txtSearchUser.setObjectName("txtSearchUser")
        self.btnSearchUser = QtWidgets.QPushButton(self.groupBox_3)
        self.btnSearchUser.setGeometry(QtCore.QRect(390, 40, 141, 41))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.btnSearchUser.setFont(font)
        self.btnSearchUser.setCursor(QtGui.QCursor(QtCore.Qt.OpenHandCursor))
        self.btnSearchUser.setStyleSheet("QPushButton#btnSearchUser {\n"
"   background-color: #371881;\n"
"   border : none;\n"
"   color: white;\n"
"   border-radius: 20px;\n"
"}")
        self.btnSearchUser.setObjectName("btnSearchUser")
        self.cbbSortUser = QtWidgets.QComboBox(self.groupBox_3)
        self.cbbSortUser.setGeometry(QtCore.QRect(750, 40, 241, 41))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.cbbSortUser.setFont(font)
        self.cbbSortUser.setStyleSheet("border-radius: 20px;\n"
"    padding-left: 15px;\n"
"    color: #371881;")
        self.cbbSortUser.setObjectName("cbbSortUser")
        self.cbbSortUser.addItem("")
        self.cbbSortUser.addItem("")
        self.cbbSortUser.addItem("")
        self.cbbSortUser.addItem("")
        self.btnSortUserIncrease = QtWidgets.QPushButton(self.groupBox_3)
        self.btnSortUserIncrease.setGeometry(QtCore.QRect(1020, 40, 141, 41))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.btnSortUserIncrease.setFont(font)
        self.btnSortUserIncrease.setCursor(QtGui.QCursor(QtCore.Qt.OpenHandCursor))
        self.btnSortUserIncrease.setStyleSheet("QPushButton#btnSortUserIncrease {\n"
"   background-color: #371881;\n"
"   border : none;\n"
"   color: white;\n"
"   border-radius: 20px;\n"
"}")
        self.btnSortUserIncrease.setIcon(icon)
        self.btnSortUserIncrease.setIconSize(QtCore.QSize(30, 30))
        self.btnSortUserIncrease.setObjectName("btnSortUserIncrease")
        self.label_8 = QtWidgets.QLabel(self.groupBox_3)
        self.label_8.setGeometry(QtCore.QRect(670, 30, 71, 61))
        self.label_8.setStyleSheet("    background-color: #e7eaed;")
        self.label_8.setText("")
        self.label_8.setPixmap(QtGui.QPixmap("d:\\PBL5\\PBL5_app\\PBL5-Car-Lisence-Plate-Recognition-Application-v2\\My-App-PBL5\\UI\\../imageUI/sort.png"))
        self.label_8.setScaledContents(True)
        self.label_8.setObjectName("label_8")
        self.label_12 = QtWidgets.QLabel(self.groupBox_3)
        self.label_12.setGeometry(QtCore.QRect(10, 30, 71, 61))
        self.label_12.setStyleSheet("    background-color: #e7eaed;")
        self.label_12.setText("")
        self.label_12.setPixmap(QtGui.QPixmap("d:\\PBL5\\PBL5_app\\PBL5-Car-Lisence-Plate-Recognition-Application-v2\\My-App-PBL5\\UI\\../imageUI/search_1.png"))
        self.label_12.setScaledContents(True)
        self.label_12.setObjectName("label_12")
        self.btnResetUser = QtWidgets.QPushButton(self.groupBox_3)
        self.btnResetUser.setGeometry(QtCore.QRect(120, 550, 171, 41))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.btnResetUser.setFont(font)
        self.btnResetUser.setCursor(QtGui.QCursor(QtCore.Qt.OpenHandCursor))
        self.btnResetUser.setStyleSheet("QPushButton#btnResetUser {\n"
"   background-color: #743de3;\n"
"   border : none;\n"
"   color: white;\n"
"   border-radius: 20px;\n"
"}")
        self.btnResetUser.setObjectName("btnResetUser")
        self.btnSortUserDecrease = QtWidgets.QPushButton(self.groupBox_3)
        self.btnSortUserDecrease.setGeometry(QtCore.QRect(1180, 40, 141, 41))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.btnSortUserDecrease.setFont(font)
        self.btnSortUserDecrease.setCursor(QtGui.QCursor(QtCore.Qt.OpenHandCursor))
        self.btnSortUserDecrease.setStyleSheet("QPushButton#btnSortUserDecrease {\n"
"   background-color: #371881;\n"
"   border : none;\n"
"   color: white;\n"
"   border-radius: 20px;\n"
"}")
        self.btnSortUserDecrease.setIcon(icon1)
        self.btnSortUserDecrease.setIconSize(QtCore.QSize(25, 25))
        self.btnSortUserDecrease.setObjectName("btnSortUserDecrease")
        self.btnAddUser.raise_()
        self.tableUser.raise_()
        self.btnUpdateUser.raise_()
        self.btnDelUser.raise_()
        self.txtSearchUser.raise_()
        self.btnSearchUser.raise_()
        self.cbbSortUser.raise_()
        self.btnSortUserIncrease.raise_()
        self.label_8.raise_()
        self.label_12.raise_()
        self.btnResetUser.raise_()
        self.btnSortUserDecrease.raise_()
        self.label_20 = QtWidgets.QLabel(self.frame_3)
        self.label_20.setGeometry(QtCore.QRect(180, 20, 391, 61))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(21)
        font.setBold(True)
        font.setWeight(75)
        self.label_20.setFont(font)
        self.label_20.setStyleSheet("QLabel {\n"
"    color: qlineargradient(spread:pad, x1:1, y1:1, x2:0, y2:0, stop:0.306818 rgba(143, 0, 146, 255), stop:0.886364 rgba(0, 100, 245, 255));\n"
" \n"
"}")
        self.label_20.setObjectName("label_20")
        self.label_5 = QtWidgets.QLabel(self.frame_3)
        self.label_5.setGeometry(QtCore.QRect(70, 0, 81, 101))
        font = QtGui.QFont()
        font.setPointSize(21)
        self.label_5.setFont(font)
        self.label_5.setText("")
        self.label_5.setPixmap(QtGui.QPixmap("d:\\PBL5\\PBL5_app\\PBL5-Car-Lisence-Plate-Recognition-Application-v2\\My-App-PBL5\\UI\\../imageUI/icons-User-manager.png"))
        self.label_5.setObjectName("label_5")
        self.label_30 = QtWidgets.QLabel(self.frame_3)
        self.label_30.setEnabled(True)
        self.label_30.setGeometry(QtCore.QRect(970, 10, 161, 91))
        self.label_30.setTabletTracking(False)
        self.label_30.setStyleSheet("QLabel {\n"
"    backround-color: red;\n"
"}\n"
"")
        self.label_30.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.label_30.setFrameShadow(QtWidgets.QFrame.Plain)
        self.label_30.setText("")
        self.label_30.setPixmap(QtGui.QPixmap("d:\\PBL5\\PBL5_app\\PBL5-Car-Lisence-Plate-Recognition-Application-v2\\My-App-PBL5\\UI\\../imageUI/icon-deco.png"))
        self.label_30.setScaledContents(True)
        self.label_30.setObjectName("label_30")
        self.label_33 = QtWidgets.QLabel(self.frame_3)
        self.label_33.setEnabled(True)
        self.label_33.setGeometry(QtCore.QRect(1230, 10, 161, 91))
        self.label_33.setTabletTracking(False)
        self.label_33.setStyleSheet("QLabel {\n"
"    backround-color: red;\n"
"}\n"
"")
        self.label_33.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.label_33.setFrameShadow(QtWidgets.QFrame.Plain)
        self.label_33.setText("")
        self.label_33.setPixmap(QtGui.QPixmap("d:\\PBL5\\PBL5_app\\PBL5-Car-Lisence-Plate-Recognition-Application-v2\\My-App-PBL5\\UI\\../imageUI/icon-deco.png"))
        self.label_33.setScaledContents(True)
        self.label_33.setObjectName("label_33")
        self.test = QtWidgets.QLabel(self.frame_3)
        self.test.setGeometry(QtCore.QRect(584, 35, 131, 41))
        self.test.setObjectName("test")
        self.user_2.addTab(self.User, "")
        CarLisence.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(CarLisence)
        self.statusbar.setObjectName("statusbar")
        CarLisence.setStatusBar(self.statusbar)

        self.retranslateUi(CarLisence)
        self.user_2.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(CarLisence)

    def retranslateUi(self, CarLisence):
        _translate = QtCore.QCoreApplication.translate
        CarLisence.setWindowTitle(_translate("CarLisence", "Car Lisence Plate Recognition Appication"))
        self.label_16.setText(_translate("CarLisence", "INFORMATION OF PEOPLE ENTERING AND LEAVING"))
        self.label_14.setText(_translate("CarLisence", "Name :"))
        self.label_15.setText(_translate("CarLisence", "License Plate :"))
        self.label_17.setText(_translate("CarLisence", "Identification System :"))
        self.label_AddUserControl.setText(_translate("CarLisence", "Not have user info? :"))
        self.btn_CreateNewUser.setText(_translate("CarLisence", "Create User"))
        self.btnOpen.setText(_translate("CarLisence", "Open"))
        self.btnCancel.setText(_translate("CarLisence", "Close"))
        self.label_19.setText(_translate("CarLisence", "CONTROL GATE"))
        self.user_2.setTabText(self.user_2.indexOf(self.controlGate), _translate("CarLisence", "Control Gate"))
        item = self.tableHistory.horizontalHeaderItem(0)
        item.setText(_translate("CarLisence", "User ID"))
        item = self.tableHistory.horizontalHeaderItem(1)
        item.setText(_translate("CarLisence", "Name"))
        item = self.tableHistory.horizontalHeaderItem(2)
        item.setText(_translate("CarLisence", "Lisence Plate"))
        item = self.tableHistory.horizontalHeaderItem(3)
        item.setText(_translate("CarLisence", "Phone Number"))
        item = self.tableHistory.horizontalHeaderItem(4)
        item.setText(_translate("CarLisence", "Time Check-in"))
        self.btnSearchHistory.setText(_translate("CarLisence", "Search"))
        self.btnSortHistoryIncrease.setText(_translate("CarLisence", "Sort"))
        self.btnSortHistoryDecrease.setText(_translate("CarLisence", "Sort"))
        self.cbbSortHistory.setItemText(0, _translate("CarLisence", "ID"))
        self.cbbSortHistory.setItemText(1, _translate("CarLisence", "Name"))
        self.cbbSortHistory.setItemText(2, _translate("CarLisence", "Phone Number"))
        self.cbbSortHistory.setItemText(3, _translate("CarLisence", "Lisence Plate"))
        self.cbbSortHistory.setItemText(4, _translate("CarLisence", "Time Check-in"))
        self.btnResetHistory.setText(_translate("CarLisence", "Reset"))
        self.btnDetailsHistory.setText(_translate("CarLisence", "Details"))
        self.label_18.setText(_translate("CarLisence", "ENTRY AND EXIT HISTORY"))
        self.user_2.setTabText(self.user_2.indexOf(self.tab), _translate("CarLisence", "History"))
        item = self.tableUser.horizontalHeaderItem(0)
        item.setText(_translate("CarLisence", "Id"))
        item = self.tableUser.horizontalHeaderItem(1)
        item.setText(_translate("CarLisence", "Name"))
        item = self.tableUser.horizontalHeaderItem(2)
        item.setText(_translate("CarLisence", "AvatarUrl"))
        item = self.tableUser.horizontalHeaderItem(3)
        item.setText(_translate("CarLisence", "Phone Number"))
        item = self.tableUser.horizontalHeaderItem(4)
        item.setText(_translate("CarLisence", "Identity Card"))
        item = self.tableUser.horizontalHeaderItem(5)
        item.setText(_translate("CarLisence", "Plate Image Url"))
        item = self.tableUser.horizontalHeaderItem(6)
        item.setText(_translate("CarLisence", "Lisence Plate"))
        self.btnAddUser.setText(_translate("CarLisence", "Add"))
        self.btnUpdateUser.setText(_translate("CarLisence", "Update"))
        self.btnDelUser.setText(_translate("CarLisence", "Delete"))
        self.btnSearchUser.setText(_translate("CarLisence", "Search"))
        self.cbbSortUser.setItemText(0, _translate("CarLisence", "ID"))
        self.cbbSortUser.setItemText(1, _translate("CarLisence", "Name"))
        self.cbbSortUser.setItemText(2, _translate("CarLisence", "Phone Number"))
        self.cbbSortUser.setItemText(3, _translate("CarLisence", "Lisence Plate"))
        self.btnSortUserIncrease.setText(_translate("CarLisence", "Sort"))
        self.btnResetUser.setText(_translate("CarLisence", "Reset"))
        self.btnSortUserDecrease.setText(_translate("CarLisence", "Sort"))
        self.label_20.setText(_translate("CarLisence", "USER MANAGERMENT "))
        self.test.setText(_translate("CarLisence", "TextLabel"))
        self.user_2.setTabText(self.user_2.indexOf(self.User), _translate("CarLisence", "User"))
import images_rc
